name: build-ios-app
on:
  push:
    branches:
      - 'cicd'
jobs:
  build:
    runs-on: macos-latest
    steps:  
      - uses: actions/checkout@v3    
      - name: Set up ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.10
      - name: Install fastlane
        run: bundle install
      - run: |
          /Users/akash/Work/projects/fastlane_test/github_actions_setup/.fvm/flutter_sdk/bin/flutter clean
          /Users/akash/Work/projects/fastlane_test/github_actions_setup/.fvm/flutter_sdk/bin/flutter build
          cd ios
          pwd
          bundle exec fastlane beta
        env:
          FLUTTER_ROOT: /Users/akash/Work/projects/fastlane_test/github_actions_setup/.fvm/flutter_sdk