name: build-ios-app
on:
  push:
    branches:
      - 'cicd'
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Setup Ruby
        run: |
          rbenv global 3.2.2
      - uses: actions/checkout@v2
      - run: cd ios
      - run: pwd
      - run: bundle exec fastlane beta
        env:
          FLUTTER_ROOT: /Users/akash/Work/projects/fastlane_test/github_actions_setup/.fvm/flutter_sdk